
FROM ubuntu:21.04

ARG DEBIAN_FRONTEND=noninteractive

# Following https://github.com/zouzias/docker-boost/blob/master/Dockerfile

ENV BOOST_VERSION=1.77.0
ENV BOOST_VERSION_=1_77_0
ENV BOOST_ROOT=/usr/include/boost

RUN apt-get -qq update && apt-get install -q -y software-properties-common
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN apt-get -qq update && apt-get install -qy g++ gcc git wget cmake libspdlog-dev python3 python3-pip gdb libssl-dev

RUN wget --max-redirect 3 https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_}.tar.gz
RUN mkdir -p /usr/include/boost && tar zxf boost_${BOOST_VERSION_}.tar.gz -C /usr/include/boost --strip-components=1

RUN mkdir /home/app
WORKDIR /home/app

RUN echo ${BOOST_ROOT}
ENTRYPOINT /bin/bash
